parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
          string $cacheDir: '%kernel.cache_dir%'

    SymfonyCodeBlockChecker\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Application.php'


